#!/usr/bin/env node
/**
 * Pre-render gallery + testimonials into the HTML files so AI/search crawlers
 * (which don't run JS) can index the content. Without this, the gallery and
 * testimonials sections look like empty <div>s in the page source.
 *
 * Inputs:  data/gallery.csv, data/testimonials.yaml
 * Outputs: rewrites regions between `<!-- BUILD:name -->` and `<!-- /BUILD:name -->`
 *          marker pairs in explore.html, explore/gallery.html, explore/testimonials.html.
 *
 * Run:     node scripts/build.js
 *
 * Gallery schema (CSV columns):
 *   src         - path to image, MUST start with "/" so the JS path-rewrite works
 *   alt         - alt text for screen readers + SEO
 *   location    - bold title in the caption
 *   date        - YYYY | YYYY-MM | YYYY-MM-DD | empty (Unlabeled)
 *   description - caption subtitle
 *
 * Testimonials schema: see data/testimonials.yaml header.
 */
const fs = require("fs");
const path = require("path");
const yaml = require("js-yaml");
const { imageSize } = require("image-size");
const { spawnSync } = require("child_process");

const ROOT = path.resolve(__dirname, "..");

// --- sibling helpers ----------------------------------------------------
// A "Cannot find module" here is nearly always an UNTRACKED helper, not a broken
// `npm install`: a file no clean checkout ever had and no blob, reflog or stash can
// restore. Two verbs, because the losses differ: need() is what GENERATION cannot run
// without; want() is a checker, and losing a checker must not also cost the site its
// build — so the site still ships, and every run says it shipped unchecked.
const missingGuards = [];
function need(mod) {
  try { return require(mod); } catch (e) {
    if (e.code !== "MODULE_NOT_FOUND") throw e;
    console.error(`\n${String(e.message).split("\n")[0]}\n\n` +
      `scripts/build.js cannot generate anything without ${mod}. Copy it back from a\n` +
      `machine that still has it, then \`git add scripts/\` so the next clone has it too.\n`);
    process.exit(1);
  }
}
function want(mod, fn) {
  let g;
  // Only a missing THIS module is tolerated; a guard that loads and then fails
  // is a real finding and must keep failing the build.
  try { g = require(mod); } catch (e) {
    if (e.code !== "MODULE_NOT_FOUND" || !String(e.message).includes(mod)) throw e;
    missingGuards.push(mod);
    return;
  }
  g[fn]();
}

// The same hazard one step earlier: the file is HERE but git does not know about it, so
// the next clean checkout is the one that breaks. Asked of git rather than of a filename
// list, so a helper added tomorrow is covered by itself, and scoped to the two tooling
// directories — a missing data file names itself in an ENOENT, a missing module does not.
// Silent without git: a tarball export has no repo and so no risk. This is the reminder;
// .githooks/pre-commit is the stop, and both ask git the same question.
function warnUntrackedBuildDeps() {
  const ls = spawnSync("git", ["ls-files", "--others", "--exclude-standard", "--", "scripts", ".githooks"],
    { cwd: ROOT, encoding: "utf8" });
  if (ls.error || ls.status !== 0) return;
  const untracked = (ls.stdout || "").split("\n").map((x) => x.trim()).filter(Boolean).sort();
  if (!untracked.length) return;
  console.warn(
    `\n!!  UNTRACKED BUILD DEPENDENC${untracked.length > 1 ? "IES" : "Y"} — never committed, so a fresh clone,\n` +
    `    \`git clean -fd\` or \`git worktree add\` loses ${untracked.length > 1 ? "them" : "it"} for good: no blob, no reflog,\n` +
    `    no stash. Commits are blocked until:  git add ${untracked.join(" ")}\n`
  );
}

const { SKIP_DIR } = need("./css-source.js");

// --- Generated-file ledger ----------------------------------------------
// The pre-commit hook has to `git add` everything this script writes, and the list can
// only stay in step if the script publishes it — a copy retyped in .githooks/pre-commit
// is how build-written pages ended up never staged.
//
//   node scripts/build.js --list-generated
//
// runs the normal build with its log on stderr and prints on stdout the repo-relative
// path of every file this build OWNS — eligible, not just changed: a file regenerated by
// hand before committing produces no write this run and must still be staged.
const GENERATED = new Set();
const LIST_MODE = process.argv.includes("--list-generated");
if (LIST_MODE) console.log = (...a) => console.error(...a);

const claim = (full) => GENERATED.add(path.relative(ROOT, full).split(path.sep).join("/"));
function writeGenerated(full, content) {
  claim(full);
  fs.writeFileSync(full, content);
}

// Read an image's pixel dimensions off disk. CSV `src` is root-anchored
// (`/images/...`); the on-disk path is ROOT + that.
function imageAspect(src) {
  if (typeof src !== "string") return 1;
  const rel = src.startsWith("/") ? src.slice(1) : src;
  const filePath = path.join(ROOT, rel);
  try {
    const { width, height } = imageSize(fs.readFileSync(filePath));
    if (!width || !height) return 1;
    return height / width;
  } catch (e) {
    console.warn(`  ! could not read dimensions for ${src}: ${e.message}`);
    return 1;
  }
}

// Greedy bin-packing: each photo goes into whichever column currently has the smallest
// summed aspect ratio, producing balanced column heights.
//
// `photos` arrives newest-first; we pack OLDEST-first and reverse each column so the
// newest still renders at the top. Packing oldest-first means the usual edit — appending
// a newer photo — is packed last and leaves every existing photo where it was, so the
// committed HTML diff is one inserted tile instead of a full reshuffle.
function distributeBalanced(photos, K) {
  const cols = Array.from({ length: K }, () => ({ items: [], total: 0 }));
  for (let i = photos.length - 1; i >= 0; i--) {
    const p = photos[i];
    let target = cols[0];
    for (let c = 1; c < cols.length; c++) {
      if (cols[c].total < target.total) target = cols[c];
    }
    target.items.push(p);
    target.total += p.aspect || 1;
  }
  return cols.map(c => c.items.reverse());
}

// --- CSV parser ---------------------------------------------------------
// Minimal RFC-4180 parser: handles quoted fields, embedded commas, CRLF,
// and "" escapes. Returns array-of-arrays including the header row.
function parseCSVGrid(text) {
  const rows = [];
  let row = [];
  let field = "";
  let inQuotes = false;
  for (let i = 0; i < text.length; i++) {
    const c = text[i];
    if (inQuotes) {
      if (c === '"') {
        if (text[i + 1] === '"') { field += '"'; i++; }
        else inQuotes = false;
      } else field += c;
    } else {
      if (c === '"') inQuotes = true;
      else if (c === ",") { row.push(field); field = ""; }
      else if (c === "\n" || c === "\r") {
        if (c === "\r" && text[i + 1] === "\n") i++;
        row.push(field); rows.push(row); row = []; field = "";
      } else field += c;
    }
  }
  if (field !== "" || row.length) { row.push(field); rows.push(row); }
  return rows.filter(r => r.some(v => v !== ""));
}

// Header row + data rows, keyed by column name. The syllabus renderer wants raw
// positional cells instead, so it calls parseCSVGrid directly.
function parseCSV(text) {
  const rows = parseCSVGrid(text);
  const header = rows.shift() || [];
  return rows.map(r => Object.fromEntries(header.map((h, i) => [h, r[i] != null ? r[i] : ""])));
}

// --- HTML escapers ------------------------------------------------------
function escapeHtml(s) {
  return String(s == null ? "" : s).replace(/[&<>"']/g, ch => ({
    "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;"
  }[ch]));
}
const escapeAttr = escapeHtml;

// --- Gallery helpers (mirror js/gallery.js) -----------------------------
function yearOf(date) {
  if (date == null || date === "") return null;
  const m = String(date).match(/^(\d{4})/);
  return m ? Number(m[1]) : null;
}

function dateSortKey(date) {
  if (date == null || date === "") return -Infinity;
  const str = String(date);
  if (/^\d{4}$/.test(str)) return new Date(`${str}-01-01`).getTime();
  if (/^\d{4}-\d{2}$/.test(str)) return new Date(`${str}-01`).getTime();
  const d = new Date(str);
  return isNaN(d) ? -Infinity : d.getTime();
}

function formatDate(date) {
  if (date == null || date === "") return "";
  const str = String(date);
  if (/^\d{4}$/.test(str)) return str;
  const ymd = str.match(/^(\d{4})-(\d{2})(?:-(\d{2}))?$/);
  if (ymd) {
    const y = Number(ymd[1]), m = Number(ymd[2]), d = Number(ymd[3] || 1);
    const dt = new Date(y, m - 1, d);
    if (!isNaN(dt)) return dt.toLocaleDateString("en-US", { year: "numeric", month: "short" });
  }
  const dt = new Date(str);
  if (!isNaN(dt)) return dt.toLocaleDateString("en-US", { year: "numeric", month: "short" });
  return str;
}

function captionLine(p) {
  return [formatDate(p.date), p.description].filter(Boolean).join(" · ");
}

// Path rewriter — matches js/gallery.js resolveSrc / js/explore.js resolveGallerySrc.
// `/images/...` → `../images/...` for pages one level deep (gallery.html, testimonials.html),
// `/images/...` → `images/...` for root-level pages (explore.html).
function resolveSrcForDepth(src, depth) {
  if (typeof src !== "string" || !src.startsWith("/")) return src;
  return depth === 1 ? ".." + src : src.slice(1);
}

// --- Gallery tile HTML --------------------------------------------------
// Every attribute here is intrinsic to the photo itself, so a tile's HTML is byte-stable
// however the gallery grows. data-chrono-idx is deliberately omitted: it shifts for every
// tile on any insert, and js/gallery.js recomputes it at runtime anyway.
function renderGalleryTile(p, depth) {
  const src = resolveSrcForDepth(p.src, depth);
  const desc = captionLine(p);
  const y = yearOf(p.date);
  const yearAttr = y != null ? String(y) : "unlabeled";
  const aspect = (p.aspect || 1).toFixed(4);
  return `        <a class="gallery-tile gallery-tile--page wow fadeInUp"
           href="${escapeAttr(src)}"
           data-year="${escapeAttr(yearAttr)}"
           data-aspect="${aspect}">
          <img src="${escapeAttr(src)}" alt="${escapeAttr(p.alt || "")}">
          <div class="gallery-tile-caption">
            <div class="loc">${escapeHtml(p.location || "")}</div>
            <div class="desc">${escapeHtml(desc)}</div>
          </div>
        </a>`;
}

function renderHiddenLightboxAnchor(p, depth) {
  const src = resolveSrcForDepth(p.src, depth);
  const desc = captionLine(p);
  const glb = `title: ${p.location || ""}; description: ${desc}`;
  return `        <a class="gallery-lightbox-source" href="${escapeAttr(src)}" data-glightbox="${escapeAttr(glb)}"></a>`;
}

// --- Testimonials helpers (mirror js/testimonials.js / js/explore.js) ---
function placementMaxYear(p) {
  const y = p && p.year;
  if (Array.isArray(y) && y.length) return Math.max(...y.filter(n => typeof n === "number"));
  if (typeof y === "number") return y;
  return 0;
}

function placementRank(medal) {
  const s = (medal || "").toLowerCase();
  if (s.includes("gold")) return 5;
  if (s.includes("silver")) return 4;
  if (s.includes("bronze")) return 3;
  if (s.includes("finalist") && !s.includes("semi")) return 2;
  if (s.includes("semifinalist")) return 1;
  return 0;
}

function medalVariant(medal) {
  const s = (medal || "").toLowerCase();
  if (s.includes("gold")) return "gold";
  if (s.includes("silver")) return "silver";
  if (s.includes("bronze")) return "bronze";
  if (s.includes("finalist") && !s.includes("semi")) return "finalist";
  if (s.includes("semifinalist")) return "semifinalist";
  return "default";
}

function formatYear(y) {
  if (typeof y === "number") return String(y);
  if (!Array.isArray(y) || y.length === 0) return String(y == null ? "" : y);
  const sorted = [...new Set(y.filter(n => typeof n === "number"))].sort((a, b) => a - b);
  if (sorted.length === 0) return "";
  const runs = [];
  let start = sorted[0], prev = sorted[0];
  for (let i = 1; i < sorted.length; i++) {
    if (sorted[i] === prev + 1) { prev = sorted[i]; continue; }
    runs.push([start, prev]);
    start = prev = sorted[i];
  }
  runs.push([start, prev]);
  return runs.map(([s, e]) => (s === e ? `${s}` : `${s}–${e}`)).join(", ");
}

function renderTestimonialBadges(placements) {
  if (!Array.isArray(placements) || placements.length === 0) return "";
  const sorted = [...placements].sort((a, b) => {
    const ya = placementMaxYear(a), yb = placementMaxYear(b);
    if (yb !== ya) return yb - ya;
    return placementRank(b.medal) - placementRank(a.medal);
  });
  return sorted.map(p => {
    const variant = medalVariant(p.medal);
    const text = `${escapeHtml(p.medal)} · ${formatYear(p.year)}`.trim();
    return `<span class="placement-badge placement-badge--${variant}">${text}</span>`;
  }).join(" ");
}

function sortTestimonialsForCarousel(data) {
  const featured = data.filter(t => t.featured);
  if (featured.length) return featured;
  return [...data].sort((a, b) => (b.year || 0) - (a.year || 0)).slice(0, 5);
}

function sortTestimonialsForGrid(data) {
  // Featured first, then by latest placement year desc.
  return [...data].sort((a, b) => {
    if (!!a.featured !== !!b.featured) return a.featured ? -1 : 1;
    const ya = Math.max(0, ...(a.placements || []).map(placementMaxYear));
    const yb = Math.max(0, ...(b.placements || []).map(placementMaxYear));
    return yb - ya;
  });
}

// data-wow-delay staggers the scroll-fade so cards don't all bubble up in unison; the
// cap keeps later cards from sitting hidden for long.
//
// These two numbers and the .toFixed(2) that formats them are the WHOLE definition of
// the stagger, and js/testimonials.js has to animate its fallback-built cards
// identically — so they are authored here once and published on the grid container as
// data-stagger-step / data-stagger-cap, the way BLOG_PAGE_SIZE is published for
// js/search.js. A retyped copy in the JS emitted "0.32000000000000004s" where this
// emits "0.32": same number, different strings, because only one side rounded.
const STAGGER_STEP = 0.08;
const STAGGER_CAP = 0.6;
const staggerDelay = (i) => Math.min((i || 0) * STAGGER_STEP, STAGGER_CAP).toFixed(2);

function renderTestimonialCard(t, i) {
  const delay = staggerDelay(i);
  return `        <article class="testimonial-card wow fadeInUp" data-wow-delay="${delay}s">
          <i class="fa-solid fa-quote-left icon mb-3"></i>
          <p class="quote">${escapeHtml((t.quote || "").trim())}</p>
          <h3 class="testimonial-name">${escapeHtml(t.name)}</h3>
          <div class="testimonial-placements">${renderTestimonialBadges(t.placements)}</div>
        </article>`;
}

function renderTestimonialSlide(t) {
  return `          <div class="text-center testimonial-content">
            <i class="fa-solid fa-quote-left icon mb-4 d-inline-block"></i>
            <p class="text-white mb-4">${escapeHtml((t.quote || "").trim())}</p>
            <h3 class="testimonial-name">${escapeHtml(t.name)}</h3>
            <div class="testimonial-placements mb-4">${renderTestimonialBadges(t.placements)}</div>
          </div>`;
}

// --- Blog helpers -------------------------------------------------------
// Date comes as MM/DD/YYYY in blogs.json.
function parseBlogDate(str) {
  if (!str) return 0;
  if (str.includes("/")) {
    const [m, d, y] = str.split("/").map(Number);
    return new Date(y, m - 1, d).getTime();
  }
  return new Date(str).getTime();
}

// Cards per page on blog-main.html. The one home for this number: it is baked
// into each card's data-page here and published on the container as
// data-page-size for js/search.js to read back.
const BLOG_PAGE_SIZE = 6;
const blogPage = (i) => Math.floor(i / BLOG_PAGE_SIZE) + 1;

// --- container attribute publishing -------------------------------------
// BLOG_PAGE_SIZE (read by js/search.js) and the testimonial stagger (read by
// js/testimonials.js) ride data attributes on their container tags, and those tags sit
// OUTSIDE the BUILD marker pairs — the markers wrap only the cards — so the attribute is
// rewritten in place and must be idempotent AND attribute-order independent.
//
// A pattern whose optional attribute group is pinned to the END of the tag matches
// nothing once the attributes are reordered: the stale attribute survives and a SECOND
// one is appended. HTML resolves a duplicate attribute by keeping the FIRST, so the
// build would silently stop controlling the value it owns.
//
// Hence: isolate the tag, delete EVERY copy of each attribute wherever it sits, then
// append exactly one of each. Splicing by offset rather than String.replace() over the
// whole document, and rebuilding the tag with a replacer FUNCTION, also keeps `$&`-style
// sequences in the markup or in a value from being read as replacement patterns.
// One rewriter for both attributes, so the bug cannot be reintroduced in a second copy.
const attrPattern = (name) =>
  new RegExp(`\\s+${name}\\s*=\\s*(?:"[^"]*"|'[^']*'|[^\\s"'<>]+)`, "gi");
const CARDS_TAG = /<[^<>]*\bdata-blog-cards-container\b[^<>]*>/;
const TESTIMONIAL_GRID_TAG = /<[^<>]*\bdata-testimonial-grid\b[^<>]*>/;

// The pure rewrite: returns the document with `attrs` normalised on the first tag
// matching `tagRe`, or null when there is no such tag to carry them.
function applyTagAttrs(html, tagRe, attrs) {
  const m = tagRe.exec(html);
  if (!m) return null;
  let tag = m[0];
  for (const name of Object.keys(attrs)) tag = tag.replace(attrPattern(name), "");
  const appended = Object.entries(attrs)
    .map(([name, value]) => ` ${name}="${escapeAttr(value)}"`).join("");
  // The captured tail preserves a self-closing `/>` and any space before the `>`.
  const rebuilt = tag.replace(/(\s*\/?)>$/, (_, tail) => `${appended}${tail}>`);
  return html.slice(0, m.index) + rebuilt + html.slice(m.index + m[0].length);
}

const applyPageSizeAttr = (html, size) =>
  applyTagAttrs(html, CARDS_TAG, { "data-page-size": size });
const applyStaggerAttrs = (html, step, cap) =>
  applyTagAttrs(html, TESTIMONIAL_GRID_TAG, { "data-stagger-step": step, "data-stagger-cap": cap });

// --- regression probe ----------------------------------------------------
// The failure this replaces is silent — a duplicate attribute renders fine and only
// shows up as a broken page 2 — so the cases are asserted on every build rather than
// described in a comment for the next refactor to "simplify" away.
// Each case is [rewrite, markup in, expected out]; the multi-attribute rows check that
// publishing two values at once is just as order-independent.
const ONE = (html) => applyPageSizeAttr(html, 9);
const TWO = (html) => applyStaggerAttrs(html, 0.08, 0.6);
const TAG_ATTR_PROBE = [
  [ONE, `<div data-blog-cards-container>`,                              `<div data-blog-cards-container data-page-size="9">`],
  [ONE, `<div data-blog-cards-container data-page-size="6">`,           `<div data-blog-cards-container data-page-size="9">`],
  // the case that appended a second attribute:
  [ONE, `<div data-blog-cards-container data-page-size="6" class="x">`, `<div data-blog-cards-container class="x" data-page-size="9">`],
  [ONE, `<div class="x" data-page-size='6' data-blog-cards-container>`, `<div class="x" data-blog-cards-container data-page-size="9">`],
  [ONE, `<div data-blog-cards-container />`,                            `<div data-blog-cards-container data-page-size="9" />`],
  [ONE, `<div data-blog-cards-container data-page-size=6 >`,            `<div data-blog-cards-container data-page-size="9" >`],
  [ONE, `<p>$& $1 keep me</p>\n<div data-blog-cards-container>`,        `<p>$& $1 keep me</p>\n<div data-blog-cards-container data-page-size="9">`],
  [TWO, `<div class="testimonials-grid" data-testimonial-grid>`,        `<div class="testimonials-grid" data-testimonial-grid data-stagger-step="0.08" data-stagger-cap="0.6">`],
  // both stale copies deleted wherever they sit, both re-appended once:
  [TWO, `<div data-stagger-cap="9" data-testimonial-grid data-stagger-step="9" class="g">`,
        `<div data-testimonial-grid class="g" data-stagger-step="0.08" data-stagger-cap="0.6">`],
];
let tagAttrsProbed = false;
function probeTagAttrs() {
  if (tagAttrsProbed) return;
  tagAttrsProbed = true;
  const bad = [];
  for (const [rewrite, input, want] of TAG_ATTR_PROBE) {
    const once = rewrite(input);
    if (once !== want) bad.push(`  in:   ${input}\n  want: ${want}\n  got:  ${once}`);
    // Idempotence is the actual contract: a second pass must be a no-op.
    const twice = rewrite(once === null ? input : once);
    if (twice !== once) bad.push(`  not idempotent: ${input}\n  pass 1: ${once}\n  pass 2: ${twice}`);
  }
  if (ONE(`<div class="blog-cards"></div>`) !== null) {
    bad.push("  a document with no [data-blog-cards-container] must return null");
  }
  if (TWO(`<div class="testimonials-grid"></div>`) !== null) {
    bad.push("  a document with no [data-testimonial-grid] must return null");
  }
  if (bad.length) {
    throw new Error(
      "applyTagAttrs SELF-TEST failed — the container rewrite is not attribute-order\n" +
      "independent or not idempotent:\n" + bad.join("\n") +
      "\n\njs/search.js reads the page size off this attribute and js/testimonials.js\n" +
      "reads the stagger off its own; a duplicate or a stale value breaks pagination\n" +
      "from page 2 onward, or desyncs the fallback animation, with nothing visibly\n" +
      "wrong on first paint."
    );
  }
}

// Throws rather than no-ops if the container is renamed, because a silent miss
// would drop js/search.js back onto its fallback and nothing would look wrong
// until page 2.
function setPageSizeAttr(html, forPath) {
  probeTagAttrs();
  const out = applyPageSizeAttr(html, BLOG_PAGE_SIZE);
  if (out === null) {
    throw new Error(`${path.relative(ROOT, forPath)} has no [data-blog-cards-container] element ` +
      `to carry data-page-size — js/search.js reads the page size from it.`);
  }
  return out;
}

// Same contract for the stagger: js/testimonials.js reads STEP and CAP off the
// grid container instead of retyping them, so a missing container silently
// returns it to a second authored copy of these numbers.
function setStaggerAttrs(html, forPath) {
  probeTagAttrs();
  const out = applyStaggerAttrs(html, STAGGER_STEP, STAGGER_CAP);
  if (out === null) {
    throw new Error(`${path.relative(ROOT, forPath)} has no [data-testimonial-grid] element ` +
      `to carry data-stagger-step / data-stagger-cap — js/testimonials.js reads the ` +
      `stagger from it.`);
  }
  return out;
}

// Which page a card sits on is STATE, so it rides data-page, which js/search.js reads —
// never a class: a class named "1" is not a valid CSS identifier (no stylesheet can
// select it without escaping it as `.\31 `), and clearing it cost the classes this build
// owns.
//
// `alt` is optional in blogs.json and defaults to "". An empty alt is right for this
// thumbnail — the card's own text carries the meaning and the whole card is one link —
// but the KEY has to exist, because js/blog-card.js and js/search.js build this same card
// from `blog.alt || ""`. Three builders, one key, one default; no alt is invented here.
function renderBlogCard(blog, opts) {
  const pageAttr = opts && opts.pageNum ? ` data-page="${opts.pageNum}"` : "";
  const tagsHtml = (blog.tags || "").split(" ").filter(Boolean)
    .map(t => `<li>${escapeHtml(t)}</li>`).join("");
  return `        <a class="card is-raised wow fadeInLeft"${pageAttr} href="${escapeAttr(blog.link)}">
          <img class="card-img-blog" src="${escapeAttr(blog.imglink)}" alt="${escapeAttr(blog.alt || "")}">
          <div class="card-label">
            <div class="header">${escapeHtml(blog.name)}</div>
            <div class="subtitle">${escapeHtml(blog.subtitle || "")}</div>
            <div class="body">${escapeHtml(blog.description)}</div>
            <ul class="taglist">${tagsHtml}</ul>
            <div class="date">${escapeHtml(blog.date)}</div>
          </div>
        </a>`;
}

// id and link are both primary keys in hand-edited blogs/blogs.json. Nothing reads `id`
// yet, which is exactly why a duplicate can sit there unnoticed until something does. A
// duplicate `link` already bites: buildSitemap() de-duplicates blog URLs through a Set,
// so two entries render two identical cards but emit one sitemap URL.
//
// ADVISORY, not fatal: a data problem in a file the build only reads must not block every
// unrelated change. It names the entries so the fix is mechanical.
function checkBlogsData(blogs) {
  const complaints = [];
  for (const key of ["id", "link"]) {
    const byValue = new Map();
    for (const b of blogs) {
      const v = b && b[key];
      if (v == null || v === "") continue;
      const k = String(v);
      if (!byValue.has(k)) byValue.set(k, []);
      byValue.get(k).push(String((b && (b.name || b.link)) || "(unnamed entry)"));
    }
    for (const [value, names] of byValue) {
      if (names.length > 1) complaints.push(`      ${key} ${value} — ${names.join("  |  ")}`);
    }
  }
  if (!complaints.length) return;
  console.warn(
    `\n!!  ADVISORY — nothing exits non-zero because of this.\n` +
    `    DUPLICATE KEY(S) IN blogs/blogs.json — the file disagrees with itself:\n` +
    complaints.join("\n") +
    `\n    Each of id/link is a primary key: id identifies the post, link is the page\n` +
    `    it renders to. Nothing reads id yet, so nothing is visibly broken — the next\n` +
    `    thing that does (an ordering, a permalink, an analytics key) inherits the\n` +
    `    ambiguity instead of finding it. A duplicate link is worse and already has\n` +
    `    an effect: two cards render, one sitemap URL is emitted.\n` +
    `    Fix: give each entry in blogs/blogs.json its own id (and its own link).\n`
  );
}

// --- Syllabus helpers ---------------------------------------------------
// The syllabus tables are pure data — nothing a visitor interacts with — so unlike the
// gallery they are baked here and never re-rendered client-side; fetched at runtime, the
// served HTML carries empty <tbody>s that no non-JS crawler can see.
//
// about/syllabus-*.csv stays the single source of truth. The <thead> stays hand-written:
// its labels are display copy and deliberately do not always match the CSV header text,
// so only <tbody> is generated.

// CSV dates are M/D/YY, always this century. Returns an ISO date — the JSON-LD schedule's
// startDate/endDate are built from these — or null for anything that is not a clean
// M/D/YY, which the caller treats as a hard error rather than emitting a wrong date.
function syllabusIsoDate(value) {
  const m = String(value == null ? "" : value).trim().match(/^(\d{1,2})\/(\d{1,2})\/(\d{2})$/);
  if (!m) return null;
  const month = Number(m[1]), day = Number(m[2]), year = 2000 + Number(m[3]);
  const dt = new Date(Date.UTC(year, month - 1, day));
  if (dt.getUTCMonth() !== month - 1 || dt.getUTCDate() !== day) return null;
  return dt.toISOString().slice(0, 10);
}

// One <tr>, mirroring what about/calendar.js builds at runtime: the Week cell is a row
// header, the rest are data cells. Short rows are padded to the <thead>'s column count so
// the table can never render ragged, and one row per line keeps the git diff to a single
// changed line per changed week.
// Dates stay PLAIN TEXT, deliberately: `time` is on trafilatura's drop-with-children list
// (so are `svg`, `figure`, `canvas`), and trafilatura is the extractor behind
// FineWeb/RefinedWeb — a <time datetime> wrapper deletes every date from the text LLMs
// train on, which is the audience this baking exists for.
function renderSyllabusRow(cells, colCount) {
  const out = [];
  for (let i = 0; i < colCount; i++) {
    const raw = cells[i] != null ? String(cells[i]).trim() : "";
    out.push(i === 0
      ? `<th scope="row">${escapeHtml(raw)}</th>`
      : `<td>${escapeHtml(raw)}</td>`);
  }
  return `                                <tr>${out.join("")}</tr>`;
}

// Count the <th scope="col"> cells in one table's <thead>, so a CSV that grows or
// loses a column fails the build instead of silently rendering a broken grid.
function syllabusHeadCols(html, tableId) {
  const re = new RegExp(`<table[^>]*id="${tableId}"[\\s\\S]*?<\\/thead>`);
  const m = html.match(re);
  if (!m) throw new Error(`No <table id="${tableId}"> with a <thead> in about/syllabus.html`);
  return (m[0].match(/<th\b/g) || []).length;
}

// Discover semesters from the CSVs themselves: syllabus-s7s2.csv drives marker
// and table id `syllabus-s7s2`. Adding a semester is then "add the CSV, add the
// table markup"; forgetting the second half throws rather than silently
// shipping an empty table for the semester currently on sale.
function syllabusSources() {
  return fs.readdirSync(path.join(ROOT, "about"))
    .map(f => f.match(/^syllabus-(s(\d+)s(\d+))\.csv$/i))
    .filter(Boolean)
    // Newest first, numerically — a string sort would put s10s1 before s5s2.
    .sort((a, b) => Number(b[2]) - Number(a[2]) || Number(b[3]) - Number(a[3]))
    .map(m => ({ file: m[0], id: m[1] }));
}

// --- Syllabus JSON-LD ---------------------------------------------------
// Generated from the same CSVs as the tables, so the structured data and the visible page
// can never disagree. It buys no Google rich result — course-info structured data was
// retired in Sept 2025 and the surviving course-list carousel wants three separately
// URL'd courses — it is here for answer engines.
const WEEKDAYS = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"];

// "s7s2" -> "Season 7 Semester 2". The ids are the only place these numbers
// live, so the label is derived rather than duplicated in a lookup table.
function syllabusLabel(id) {
  const m = String(id).match(/^s(\d+)s(\d+)$/i);
  return m ? `Season ${m[1]} Semester ${m[2]}` : id;
}

function buildSyllabusJsonLd(semesters) {
  const instances = semesters.map(sem => {
    const start = sem.dates[0], end = sem.dates[sem.dates.length - 1];
    const years = start.slice(0, 4) === end.slice(0, 4)
      ? start.slice(0, 4)
      : `${start.slice(0, 4)}–${end.slice(0, 4)}`;
    return {
      "@type": "CourseInstance",
      name: `${syllabusLabel(sem.id)} (${years})`,
      courseMode: "Online",
      courseSchedule: {
        "@type": "Schedule",
        startDate: start,
        endDate: end,
        repeatFrequency: "P1W",
        // Every lecture falls on the same weekday; derive it from the first date
        // rather than hardcoding, so a future schedule change can't lie here.
        byDay: `https://schema.org/${WEEKDAYS[new Date(start + "T00:00:00Z").getUTCDay()]}`,
      },
    };
  });

  // Newest semester first — the sections describe the course as taught now.
  const current = semesters[0];
  const sections = current.rows.map(r => {
    // Everything after the topic column becomes the description, labelled with
    // its own <thead> wording so the JSON reads the way the table does.
    const detail = current.header
      .map((h, i) => (i <= current.dateIdx || i === current.topicIdx
        ? null
        : `${String(h).trim()}: ${String(r[i] || "").trim()}`))
      .filter(t => t && !/:\s*$/.test(t))
      .join(" · ");
    const section = {
      "@type": "Syllabus",
      position: Number(r[0]) || undefined,
      name: String(r[current.topicIdx] || "").trim(),
    };
    if (detail) section.description = detail;
    return section;
  }).filter(sec => sec.name);

  const doc = {
    "@context": "https://schema.org",
    "@type": "Course",
    "@id": `${SITE}/about/syllabus.html#course`,
    name: "Baology Prep USABO Course",
    url: `${SITE}/about/syllabus.html`,
    description:
      "A year-round, two-semester online biology course preparing high school students " +
      "for the USA Biology Olympiad (USABO), taught by past USABO finalists and IBO " +
      "medalists. Each semester runs 20 weekly lectures mapped to Campbell Biology chapters.",
    provider: { "@type": "Organization", name: "Baology Prep", url: `${SITE}/` },
    hasCourseInstance: instances,
    syllabusSections: sections,
  };
  return `    <script type="application/ld+json">\n` +
    JSON.stringify(doc, null, 2).split("\n").map(l => "    " + l).join("\n") +
    `\n    </script>`;
}

// --- Class types --------------------------------------------------------
// data/classes.yaml is the source of truth for what each weekly class IS, who teaches it,
// when it meets and which tiers include it.
const WEEK_FROM_SAT = ["Saturday", "Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday"];

// The course week starts with Saturday's Main Lecture, so the list reads as a
// week rather than in whatever order the file happens to be in.
function sortClassesByWeek(classes) {
  return [...classes].sort((a, b) => WEEK_FROM_SAT.indexOf(a.day) - WEEK_FROM_SAT.indexOf(b.day));
}

// "20:00" -> "8:00pm ET / 5:00pm PT". Pacific is derived, never stored: both
// zones shift for DST together, so ET-3 holds year-round. Rendering the zone as
// ET (not EST) is likewise correct in both halves of the season.
function classTime(startEt) {
  const [h, m] = String(startEt).split(":").map(Number);
  const fmt = (x) => `${(x % 12) || 12}:${String(m).padStart(2, "0")}${x < 12 ? "am" : "pm"}`;
  return `${fmt(h)} ET / ${fmt((h + 21) % 24)} PT`;
}

// Class names on these lines must not contain "meta": trafilatura discards elements whose
// class matches its boilerplate patterns, and a class reading as a byline/timestamp
// silently deleted the day, time and instructor from the extracted text.
function renderClassItem(c) {
  return `              <li><a href="about.html#${escapeAttr(c.anchor)}">${escapeHtml(c.name)}</a></li>`;
}

// Just the class name, for the index staff cards under each instructor's name.
function renderTeachesShort(classes, personAnchor) {
  const mine = classes.filter(c => c.anchor === personAnchor);
  if (!mine.length) return "";
  return `            <span class="instructor-class">${escapeHtml(mine.map(c => c.name).join(" · "))}</span>`;
}

// Tier membership comes from each class's `levels`, so the cards and the class
// list can never disagree about what a tier includes.
function renderTier(classes, tier) {
  const inTier = tier === "full" ? classes : classes.filter(c => (c.levels || []).includes(tier));
  return sortClassesByWeek(inTier).map(renderClassItem).join("\n");
}

// One instructor's teaching line for their about.html card. The signup tiers link
// here, so this is where the day/time/description actually live — stated once.
function renderTeaches(classes, personAnchor) {
  const mine = classes.filter(c => c.anchor === personAnchor);
  if (!mine.length) return "";
  // The "Teaches" label is load-bearing: without a verb, the class description
  // reads as a continuation of the instructor's biography.
  return mine.map(c =>
    `                    <p class="teaches">` +
    `<span class="teaches-label">Teaches</span>` +
    `<span class="teaches-name">${escapeHtml(c.name)}</span>` +
    `<span class="teaches-when">${escapeHtml(c.day)}s, ${escapeHtml(classTime(c.startEt))}</span>` +
    `<span class="teaches-desc">${escapeHtml(String(c.description).trim())}</span>` +
    `</p>`
  ).join("\n");
}

// --- Results chart ------------------------------------------------------
// data/results.csv is the single source of truth for every finalist/IBO count on the
// site; the chart, the totals row and the prose summary are all summed from it, and
// checkResultClaims() below fails the build if a page states a total that disagrees.
// USABO invites 20 National Finalists a year and Team USA takes 4 of them. Bars are drawn
// against those, not against our best year: a share of the actual national field is both
// the honest denominator and the stronger claim.
const FIELD_FINALISTS = 20;
const FIELD_IBO = 4;

function resultsTotals(rows) {
  return rows.reduce((t, r) => ({
    finalists: t.finalists + Number(r[1] || 0),
    ibo: t.ibo + Number(r[2] || 0),
  }), { finalists: 0, ibo: 0 });
}

// One row: year, a nested bar with the finalist count printed beside it, and the
// IBO count. Bar widths are a share of the national field (FIELD_* above), so a bar
// reads as "this fraction of every finalist in the country".
function renderResultsRow(r) {
  const [year, fin, ibo] = [String(r[0]).trim(), Number(r[1]), Number(r[2])];
  const finPct = ((fin / FIELD_FINALISTS) * 100).toFixed(1);
  const iboPct = ((ibo / fin) * 100).toFixed(1);
  return `            <tr>` +
    `<th scope="row">${escapeHtml(year)}</th>` +
    `<td><span class="rc-cell"><span class="rc-track">` +
      `<span class="rc-fill" style="width:${finPct}%">` +
        `<span class="rc-ibo" style="width:${iboPct}%"></span>` +
      `</span></span>` +
      `<span class="rc-val">${fin}<span class="rc-of">/${FIELD_FINALISTS}</span></span></span></td>` +
    `<td><span class="rc-val">${ibo}<span class="rc-of">/${FIELD_IBO}</span></span></td>` +
    `</tr>`;
}

function renderResultsChart(rows) {
  const t = resultsTotals(rows);
  const first = String(rows[0][0]).trim(), last = String(rows[rows.length - 1][0]).trim();
  const capF = rows.length * FIELD_FINALISTS, capI = rows.length * FIELD_IBO;
  const shareF = Math.round((t.finalists / capF) * 100);
  const shareI = Math.round((t.ibo / capI) * 100);
  // "every season" is derived, not asserted: a future zero row drops the clause instead of
  // letting the sentence go quietly false.
  const everySeason =
    rows.every(r => Number(r[1]) > 0) && rows.every(r => Number(r[2]) > 0);
  // The totals are restated in the caption as prose because jusText (Nemotron-CC's
  // extractor) discards tables as boilerplate but keeps the caption. No digits in the lead:
  // checkResultClaims() guards "<number> ... Team USA", and a count there would be a second
  // place for the same figure to drift.
  // Split in two so the lead can be BOLD: each half is escaped on its own and the <b> added
  // outside, since escapeHtml() over the whole caption would render the tag literally.
  const captionLead =
    `Baology students win an outsized share of the country's top biology olympiad places` +
    (everySeason ? `, in every season we have run` : ``) + `.`;
  const caption =
    `Below is a table of Baology Prep USA Biology Olympiad results by season, ${first} to ${last}. ` +
    `USABO names ${FIELD_FINALISTS} National Finalists each year and Team USA takes ${FIELD_IBO} of them; ` +
    `each bar shows how many of that season's ${FIELD_FINALISTS} came from a Baology class. ` +
    `Across ${rows.length} seasons Baology students took ${t.finalists} of the ${capF} finalist places ` +
    `(${shareF}%) and ${t.ibo} of the ${capI} Team USA places (${shareI}%).`;
  const legend = [
    `        <div class="rc-legend">`,
    `          <span class="rc-key"><span class="rc-swatch rc-swatch--finalist"></span>USABO National Finalists</span>`,
    `          <span class="rc-key"><span class="rc-swatch rc-swatch--ibo"></span>Team USA at the IBO (selected from the finalists)</span>`,
    `        </div>`,
  ].join("\n");
  return [
    `        <table class="results-table">`,
    `          <caption><b>${escapeHtml(captionLead)}</b> ${escapeHtml(caption)}</caption>`,
    `          <thead>`,
    `            <tr><th scope="col">Season</th><th scope="col">USABO National Finalists</th><th scope="col">Team USA (IBO)</th></tr>`,
    `          </thead>`,
    `          <tbody>`,
    rows.map(r => renderResultsRow(r)).join("\n"),
    `          </tbody>`,
    `          <tfoot>`,
    `            <tr class="rc-total"><th scope="row">Total<span class="rc-of">${escapeHtml(first)}&ndash;${escapeHtml(last)}</span></th>` +
      `<td><span class="rc-big">${t.finalists}</span><span class="rc-share">${shareF}% of all ${capF}</span></td>` +
      `<td><span class="rc-big">${t.ibo}</span><span class="rc-share">${shareI}% of all ${capI}</span></td></tr>`,
    `          </tfoot>`,
    `        </table>`,
    legend,
  ].join("\n");
}

// --- Signup disclaimer ---------------------------------------------------
// The refund deadline is the day BEFORE the first lecture, and it is derived rather than typed so it
// cannot disagree with the countdown popup: js/site-config.js's courseStartIso is the only place the
// course start is written down, and js/countdown-popup.js reads the same value. Move the course and
// this sentence moves with it.
function courseStartParts() {
  const src = fs.readFileSync(path.join(ROOT, "js/site-config.js"), "utf8");
  const m = src.match(/courseStartIso:\s*"(\d{4})-(\d{2})-(\d{2})T/);
  if (!m) {
    throw new Error(
      "js/site-config.js: courseStartIso is missing or is not an ISO date.\n" +
      "The signup refund deadline is derived from it, so the build cannot continue."
    );
  }
  return { y: +m[1], m: +m[2], d: +m[3] };
}

function renderSignupDisclaimer() {
  const { y, m, d } = courseStartParts();
  // Date.UTC on the calendar date only: using local time would let the build machine's timezone push
  // the subtraction across a day boundary and quietly print the wrong deadline.
  const dl = new Date(Date.UTC(y, m - 1, d) - 86400000);
  const deadline = `${dl.getUTCMonth() + 1}/${dl.getUTCDate()}/${dl.getUTCFullYear()}`;
  return [
    `      <p class="step-note step-note--section text-center">Refunds are not offered after ${deadline}. Levels`,
    `        cannot be switched once the course has started. Baology makes no promises as to the outcomes,`,
    `        results, or progress of students who are enrolled in the course. We are not in any way affiliated`,
    `        with the USA Biology Olympiad or the Center for Excellence in Education.</p>`,
  ].join("\n");
}

// The whole "See Our Results" section, not just the chart, so index.html and signup.html cannot drift
// apart. The two wrappers were byte-identical by hand-discipline alone; now one function emits both and
// the marker pair in each page is all that page owns. Anything about this section — heading, animation,
// column width — is changed HERE, once.
function renderResultsSection(rows) {
  return [
    `  <section class="section" id="results">`,
    `    <div class="container">`,
    `      <div class="row">`,
    `        <div class="col-lg-10 mx-auto">`,
    `          <h2 class="text-secondary text-center mb-3 wow fadeInDown" data-wow-delay=".2s">See Our Results</h2>`,
    `          <!-- The chart animates as ONE block: the caption is a child of the table element, so it`,
    `               cannot fade separately from the rows it introduces. fadeInUp under the h2's fadeInDown`,
    `               is the pairing every other section uses, at the .3s the section intros carry. -->`,
    `          <div class="table-responsive wow fadeInUp" data-wow-delay=".3s">`,
    renderResultsChart(rows),
    `          </div>`,
    `        </div>`,
    `      </div>`,
    `    </div>`,
    `  </section>`,
  ].join("\n");
}

// Every page that states a finalist/IBO total must match data/results.csv, including the
// invisible ones in <meta> tags.
function checkResultClaims(totals) {
  // Anchored deliberately tightly: a loose "(\\d+) ... finalist" also matches a YEAR
  // ("2019 USABO Finalist"), a rank ("Top 20 National Finalist") and the size of the
  // national field ("only 20 finalists") — correct sentences that are not our total. An
  // aggregate claim always puts the competition name immediately after the count, and
  // (?<!\d) stops \d{1,3} matching "019" inside "2019".
  const FINALISTS = /(?<!\d)(\d{1,3})\s+(?:USABO|USA Biology Olympiad)[^.]{0,48}?[Ff]inalist/g;
  // Allows text between the count and "Team USA" ("12 of which went on to represent Team
  // USA" — the caption this build writes) but forbids a digit in between, so
  // "52 ... Finalist places, 12 of which ... Team USA" matches only the 12.
  const TEAM_USA = /(?<!\d)(\d{1,3})\s+[^.<0-9]{0,70}?Team USA/g;
  const bad = [];
  const walk = (dir) => {
    for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
      if (SKIP_DIR.test(e.name)) continue;
      const full = path.join(dir, e.name);
      if (e.isDirectory()) { walk(full); continue; }
      if (!e.name.endsWith(".html")) continue;
      const raw = fs.readFileSync(full, "utf8");
      const rel = path.relative(ROOT, full);
      // Only HAND-WRITTEN copy can drift. Regions between BUILD markers are derived from
      // the CSV, and the chart's own caption cites the national field size ("20 National
      // Finalists each year"), which is not our total — so they are blanked before scanning.
      const txt = raw.replace(/<!--\s*BUILD:[\w-]+\s*-->[\s\S]*?<!--\s*\/BUILD:[\w-]+\s*-->/g,
        (m) => m.replace(/[^\n]/g, " "));
      const line = (i) => txt.slice(0, i).split("\n").length;
      for (const m of txt.matchAll(FINALISTS)) {
        if (Number(m[1]) !== totals.finalists) {
          bad.push(`${rel}:${line(m.index)}  claims ${m[1]} finalists, data/results.csv says ${totals.finalists}`);
        }
      }
      for (const m of txt.matchAll(TEAM_USA)) {
        if (Number(m[1]) !== totals.ibo) {
          bad.push(`${rel}:${line(m.index)}  claims ${m[1]} Team USA, data/results.csv says ${totals.ibo}`);
        }
      }
    }
  };
  walk(ROOT);
  if (bad.length) {
    throw new Error("results claim guard failed:\n  - " + bad.join("\n  - ") +
      "\n\nEvery count comes from data/results.csv. Update the CSV, not the copy.");
  }
  console.log(`Results claim guard OK — every stated total matches data/results.csv (${totals.finalists}/${totals.ibo})`);
}

// --- Sitemap ------------------------------------------------------------
// Regenerate sitemap.xml (+ image sitemap) so search/AI crawlers can discover every page
// and every gallery image. Output is fully deterministic — no build-time or filesystem
// timestamps anywhere — so two clones of one commit produce byte-identical sitemaps and
// the file changes only when the page list, the photos, or a page's last COMMIT date does.
const SITE = "https://baology.org";

// --- robots meta --------------------------------------------------------
// A page whose own head says `<meta name="robots" content="noindex">` must not also be
// submitted in sitemap.xml: the two contradict each other and the page wins, so the entry
// is at best noise.
//
// Read from the page itself rather than a hardcoded exclusion list, so noindexing the next
// page is one tag edit and the sitemap follows with nobody in the loop. Scoped to <head>,
// the only place a crawler honours the tag, and with HTML comments stripped first so a
// commented-out tag cannot silently delete a live URL. `none` counts: the spec defines it
// as shorthand for "noindex, nofollow".
const META_TAG = /<meta\b(?:"[^"]*"|'[^']*'|[^<>])*>/gi;

function attrValue(tag, name) {
  // (?<![-\w]) so `data-name=` / `itemprop-name=` is not read as `name=`.
  const m = new RegExp(`(?<![-\\w])${name}\\s*=\\s*(?:"([^"]*)"|'([^']*)'|([^\\s"'=<>\`]+))`, "i").exec(tag);
  if (!m) return null;
  return m[1] != null ? m[1] : m[2] != null ? m[2] : m[3];
}

function htmlIsNoindex(html) {
  const head = /<head\b[^<>]*>([\s\S]*?)<\/head>/i.exec(html);
  const scope = (head ? head[1] : html).replace(/<!--[\s\S]*?-->/g, "");
  META_TAG.lastIndex = 0;
  for (const m of scope.matchAll(META_TAG)) {
    if ((attrValue(m[0], "name") || "").trim().toLowerCase() !== "robots") continue;
    const directives = (attrValue(m[0], "content") || "")
      .toLowerCase().split(",").map((d) => d.trim());
    if (directives.includes("noindex") || directives.includes("none")) return true;
  }
  return false;
}

// This reader failing is SILENT — a regex that stops matching quietly puts noindexed URLs
// back into the sitemap, and nobody reads sitemap.xml — so its cases are asserted on every
// build rather than described in a comment.
const NOINDEX_PROBE = [
  [`<head><meta name="robots" content="noindex"></head>`, true],
  [`<head><meta content="noindex" name="robots"></head>`, true],   // attribute order
  [`<head><meta name=robots content=noindex></head>`, true],       // unquoted
  [`<head><meta name='robots' content='NOINDEX, follow'></head>`, true],
  [`<head><meta name="ROBOTS" content="none"></head>`, true],      // spec shorthand
  [`<head><meta name="robots" content="index, follow"></head>`, false],
  [`<head><meta name="robots" content="max-image-preview:large"></head>`, false],
  // "noindex" appearing as prose in some OTHER meta must not exclude the page:
  [`<head><meta name="description" content="what noindex, none mean"></head>`, false],
  // a commented-out tag is not a live tag:
  [`<head><!-- <meta name="robots" content="noindex"> --></head>`, false],
  // ...and neither is one quoted in the body:
  [`<head><title>x</title></head><body><pre>&lt;meta name="robots" content="noindex"&gt;</pre></body>`, false],
  [`<head><meta name="description" content="a > b"><meta name="robots" content="noindex"></head>`, true],
  [`<html><head></head><body></body></html>`, false],
  // a look-alike attribute name is not the attribute:
  [`<head><meta data-name="robots" content="noindex"></head>`, false],
];
let noindexProbed = false;
function probeNoindex() {
  if (noindexProbed) return;
  noindexProbed = true;
  const bad = NOINDEX_PROBE
    .filter(([html, want]) => htmlIsNoindex(html) !== want)
    .map(([html, want]) => `  want ${want}: ${html}`);
  if (bad.length) {
    throw new Error(
      "robots-meta reader SELF-TEST failed — sitemap.xml would be built from a\n" +
      "wrong answer about which pages are noindexed:\n" + bad.join("\n")
    );
  }
}

// File-level wrapper: unreadable means "cannot prove it is noindexed", so the URL
// stays — but say so, because a sitemap entry whose file is not on disk is a 404
// handed to a crawler and that is worth hearing about too.
function pageIsNoindex(file) {
  probeNoindex();
  try {
    return htmlIsNoindex(fs.readFileSync(path.join(ROOT, file), "utf8"));
  } catch (e) {
    console.warn(`  ! sitemap: could not read ${file} to check its robots meta: ${e.message}`);
    return false;
  }
}

// --- lastmod ------------------------------------------------------------
// The date a URL last changed, read from GIT, not from the filesystem. mtime is a property
// of the checkout, not of the content, so two clones of one commit would disagree and any
// checkout would mint dates it did not earn. A wrong lastmod is worse than none: crawlers
// that catch a sitemap lying about it stop trusting the field. `%cs` (committer date) is
// stored in the commit object, so every clone of a commit agrees.
//
// One `git log` for the whole page list. Files with no commit yet, and every file when git
// is unavailable (a tarball export), get NO <lastmod> — omitting it is the honest answer.
//
// Known and accepted: the date lags by one commit for a page whose own edit is the change
// being committed, because the pre-commit hook builds before that commit exists. It
// self-corrects on the next build.
function gitLastMod(files) {
  const dates = new Map();
  if (!files.length) return dates;
  const log = spawnSync("git",
    ["log", "--format=%x00%cs", "--name-only", "--", ...files],
    { cwd: ROOT, encoding: "utf8", maxBuffer: 32 * 1024 * 1024 });
  if (log.error || log.status !== 0) {
    console.warn("  ! sitemap: git unavailable — every <lastmod> omitted.");
    return dates;
  }
  const want = new Set(files);
  // Records are newest-first and NUL-delimited: "<date>\n\n<path>\n<path>…".
  // First record naming a path wins; later (older) records cannot overwrite it.
  for (const rec of log.stdout.split("\0")) {
    const lines = rec.split("\n").map((l) => l.trim()).filter(Boolean);
    const date = lines.shift();
    if (!/^\d{4}-\d{2}-\d{2}$/.test(date || "")) continue;
    for (const f of lines) if (want.has(f) && !dates.has(f)) dates.set(f, date);
  }
  return dates;
}

function buildSitemap(photos, blogs) {
  // Hand-maintained list of top-level pages (excludes the header.html fragment
  // and unpublished sample blog files). 404.html is excluded by its own
  // `<meta name="robots" content="noindex">`, like every other noindexed page —
  // see the filter below.
  const pages = [
    { url: "/", file: "index.html" },
    { url: "/about.html", file: "about.html" },
    { url: "/about/faq.html", file: "about/faq.html" },
    { url: "/about/syllabus.html", file: "about/syllabus.html" },
    { url: "/signup.html", file: "signup.html" },
    { url: "/demo/", file: "demo/index.html" },
    { url: "/explore.html", file: "explore.html" },
    { url: "/explore/testimonials.html", file: "explore/testimonials.html" },
    { url: "/blog-main.html", file: "blog-main.html" },
  ];
  // Published blog posts — only those linked from blogs.json. De-duplicated
  // and sorted so the order is stable across builds.
  const blogPages = [...new Set(blogs.map(b => "/" + String(b.link).replace(/^\/+/, "")))]
    .sort()
    .map((url) => ({ url, file: url.slice(1) }));

  // The gallery page carries an <image:image> entry per photo. Sorted by src
  // so adding/editing a caption doesn't reorder the whole block.
  const imageEntries = [...photos]
    .sort((a, b) => (a.src < b.src ? -1 : a.src > b.src ? 1 : 0))
    .map(p => {
      const title = (p.location || "").trim();
      const caption = (p.description || p.alt || "").trim();
      return [
        `    <image:image>`,
        `      <image:loc>${escapeHtml(SITE + p.src)}</image:loc>`,
        title ? `      <image:title>${escapeHtml(title)}</image:title>` : null,
        caption ? `      <image:caption>${escapeHtml(caption)}</image:caption>` : null,
        `    </image:image>`,
      ].filter(Boolean).join("\n");
    })
    .join("\n");

  // The gallery goes through the same filter as everything else — one list, one
  // rule — so noindexing it would drop its image entries with it rather than
  // leaving them behind in a hand-written special case.
  const gallery = { url: "/explore/gallery.html", file: "explore/gallery.html", images: imageEntries };

  const skipped = [];
  const indexed = [...pages, ...blogPages, gallery].filter((e) => {
    if (!pageIsNoindex(e.file)) return true;
    skipped.push(e.url);
    return false;
  });
  const lastmods = gitLastMod(indexed.map((e) => e.file));
  const urls = indexed
    .map(({ url, file, images }) => {
      const lastmod = lastmods.get(file);
      const lastmodTag = lastmod ? `\n    <lastmod>${lastmod}</lastmod>` : "";
      const imageBlock = images ? `\n${images}` : "";
      return `  <url>\n    <loc>${escapeHtml(SITE + url)}</loc>${lastmodTag}${imageBlock}\n  </url>`;
    });

  const xml = [
    `<?xml version="1.0" encoding="UTF-8"?>`,
    `<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"`,
    `        xmlns:image="http://www.google.com/schemas/sitemap-image/1.1">`,
    urls.join("\n"),
    `</urlset>`,
    ``,
  ].join("\n");
  return { xml, skipped };
}

// --- Marker injection ---------------------------------------------------
function injectBetweenMarkers(html, name, content) {
  const open = `<!-- BUILD:${name} -->`;
  const close = `<!-- /BUILD:${name} -->`;
  const re = new RegExp(`${open.replace(/[.*+?^${}()|[\\]\\\\]/g, "\\$&")}[\\s\\S]*?${close.replace(/[.*+?^${}()|[\\]\\\\]/g, "\\$&")}`, "g");
  if (!re.test(html)) {
    throw new Error(`Marker pair not found: ${name}`);
  }
  re.lastIndex = 0;
  return html.replace(re, `${open}\n${content}\n        ${close}`);
}

// --- Static nav sync (header.html is the single source) -----------------
// Every page carries its nav as static, crawlable HTML; this keeps them all in
// sync with header.html on each build. Replaces either an inlined
// <header class="navigation…">…</header> block or a <div id="header"></div>
// placeholder, so a new page only needs one of those where the nav belongs.
function syncNav() {
  const nav = fs.readFileSync(path.join(ROOT, "header.html"), "utf8").trim();
  const navRe = /<header class="navigation[\s\S]*?<\/header>/;
  // header.html must be EXACTLY one <header> element. Anything outside it — a leading comment, say —
  // gets copied into every page but is not matched by navRe on the next build, so each build appends
  // another copy and never removes the old one. That happened: a 919-byte comment reached 5 copies on
  // each of 20 pages before it was caught. Put such comments INSIDE <header>.
  if (!/^<header class="navigation[\s\S]*<\/header>$/.test(nav)) {
    throw new Error(
      "header.html has content outside its <header> element.\n" +
      "syncNav() copies the whole file in but only matches <header>...</header> on the way back out,\n" +
      "so anything outside it accumulates one more copy per build. Move it inside <header>."
    );
  }
  const placeholderRe = /<div id="header">\s*<\/div>/;
  const skipFiles = new Set(["header.html", "footer.html"]);
  let count = 0;
  (function walk(dir) {
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      if (entry.name.startsWith(".")) continue;
      const full = path.join(dir, entry.name);
      if (entry.isDirectory()) {
        if (!SKIP_DIR.test(entry.name)) walk(full);
        continue;
      }
      if (!entry.name.endsWith(".html")) continue;
      if (skipFiles.has(path.relative(ROOT, full))) continue;
      const html = fs.readFileSync(full, "utf8");
      let out = html;
      if (navRe.test(out)) out = out.replace(navRe, nav);
      else if (placeholderRe.test(out)) out = out.replace(placeholderRe, nav);
      else continue;                 // no nav here — not a page this build owns
      claim(full);
      if (out !== html) { fs.writeFileSync(full, out); count++; }
    }
  })(ROOT);
  console.log(`Synced static nav into ${count} page(s) from header.html`);
}

// --- Build ---------------------------------------------------------------
// Overlay dims (--scrim-lightbox / --scrim-modal) override vendor CSS by load order alone.
// A plugin upgrade can reintroduce a hardcoded dim or move it to a new, more specific
// selector, and nothing would notice until someone opened the lightbox on a phone — so
// fail the build instead. The fingerprint hashes the SET of vendor rules that paint a dim,
// not each rule individually, which is what catches a brand-new selector being added.
const SCRIM_VENDOR_FINGERPRINT = "e5732dbdb087";

function checkScrims() {
  const crypto = require("crypto");
  const vendorFiles = [
    "plugins/glightbox/glightbox.min.css",
    "plugins/bootstrap/bootstrap.min.css",
  ];
  // Matches innermost rules only, so @media-nested rules are captured too.
  // Note: a regex that consumes its leading delimiter skips every other rule in
  // a minified file. This form does not.
  const RULE = /([^{}]+)\{([^{}]*)\}/g;
  const found = [];
  for (const rel of vendorFiles) {
    const css = fs.readFileSync(path.join(ROOT, rel), "utf8");
    let m;
    RULE.lastIndex = 0;
    while ((m = RULE.exec(css)) !== null) {
      const sel = m[1].trim(), body = m[2].trim();
      if (!/goverlay|modal-backdrop/.test(sel)) continue;
      if (!/(^|;)\s*(background|background-color|opacity)\s*:/.test(";" + body)) continue;
      found.push(`${rel}|${sel}{${body}}`);
    }
  }
  const fp = crypto.createHash("sha256")
    .update(found.sort().join("\n")).digest("hex").slice(0, 12);

  const errors = [];
  if (fp !== SCRIM_VENDOR_FINGERPRINT) {
    errors.push(
      `vendor scrim rules changed (pinned ${SCRIM_VENDOR_FINGERPRINT}, found ${fp}).\n` +
      `  ${found.length} vendor rule(s) currently paint a dim:\n` +
      found.map((f) => "    " + f).join("\n")
    );
  }

  const site = fs.readFileSync(path.join(ROOT, "css/style.css"), "utf8");
  const required = [
    [".goverlay", "--scrim-lightbox"],
    [".glightbox-mobile .goverlay", "--scrim-lightbox"],
    [".modal-backdrop", "--scrim-modal"],
    [".modal-backdrop.show", null],
  ];
  for (const [sel, token] of required) {
    const esc = sel.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
    if (!new RegExp(`(^|,|\\})\\s*${esc}\\s*(,|\\{)`, "m").test(site)) {
      errors.push(`css/style.css has no override for \`${sel}\``);
    }
    if (token && !site.includes(`var(${token}`)) {
      errors.push(`css/style.css never references var(${token})`);
    }
  }
  for (const t of ["--scrim-lightbox", "--scrim-modal"]) {
    if (!new RegExp(`^\\s*${t}\\s*:`, "m").test(site)) {
      errors.push(`token ${t} is not defined in :root`);
    }
  }
  if (!/\.modal-backdrop\.show\s*\{[^}]*opacity\s*:\s*1\b/.test(site)) {
    errors.push("`.modal-backdrop.show { opacity: 1 }` is missing — Bootstrap's .5 would multiply --scrim-modal's alpha");
  }

  if (errors.length) {
    throw new Error(
      "scrim guard failed:\n  - " + errors.join("\n  - ") +
      "\n\nThe overlay dims are tokenized in css/style.css (:root --scrim-*).\n" +
      "Re-audit the vendor rules listed above, point the --scrim-* overrides at\n" +
      "them (matching or beating their specificity), then update\n" +
      "SCRIM_VENDOR_FINGERPRINT in scripts/build.js."
    );
  }
  console.log(`Scrim guard OK — vendor fingerprint ${fp}, ${found.length} vendor dim rule(s) overridden`);
}

function build() {
  checkScrims();
  want("./color-guard.js", "checkColors");
  want("./spacing-guard.js", "checkSpacing");
  want("./radius-guard.js", "checkRadius");
  want("./type-guard.js", "checkType");
  syncNav();
  const galleryCsv = fs.readFileSync(path.join(ROOT, "data/gallery.csv"), "utf8");
  const photos = parseCSV(galleryCsv)
    .sort((a, b) => dateSortKey(b.date) - dateSortKey(a.date));

  // Tag each photo with its aspect ratio (height/width) read from disk, for the
  // data-aspect attribute and for the column-balanced distribution below.
  photos.forEach((p) => {
    p.aspect = imageAspect(p.src);
  });

  const testimonialsYaml = fs.readFileSync(path.join(ROOT, "data/testimonials.yaml"), "utf8");
  const testimonials = yaml.load(testimonialsYaml, { schema: yaml.CORE_SCHEMA });

  // --- gallery.html ---------------------------------------------------
  const galleryHtmlPath = path.join(ROOT, "explore/gallery.html");
  let galleryHtml = fs.readFileSync(galleryHtmlPath, "utf8");
  const K = 3;
  const distributedCols = distributeBalanced(photos, K);
  const colTotals = distributedCols.map(col => col.reduce((s, p) => s + (p.aspect || 1), 0));
  const galleryTiles = distributedCols
    .map(col => {
      const tiles = col.map(p => renderGalleryTile(p, /*depth*/ 1)).join("\n");
      return `      <div class="gallery-col">\n${tiles}\n      </div>`;
    })
    .join("\n");
  const lightboxAnchors = photos.map(p => renderHiddenLightboxAnchor(p, /*depth*/ 1)).join("\n");
  galleryHtml = injectBetweenMarkers(galleryHtml, "gallery-grid", galleryTiles);
  galleryHtml = injectBetweenMarkers(galleryHtml, "gallery-lightbox-sources", lightboxAnchors);
  writeGenerated(galleryHtmlPath, galleryHtml);
  console.log(`Wrote explore/gallery.html — ${photos.length} tiles (col heights: ${colTotals.map(t => t.toFixed(2)).join(", ")}) + ${photos.length} lightbox sources`);

  // --- testimonials.html ----------------------------------------------
  const testimonialsHtmlPath = path.join(ROOT, "explore/testimonials.html");
  let testimonialsHtml = fs.readFileSync(testimonialsHtmlPath, "utf8");
  const cards = sortTestimonialsForGrid(testimonials).map(renderTestimonialCard).join("\n");
  testimonialsHtml = injectBetweenMarkers(testimonialsHtml, "testimonials-grid", cards);
  // The stagger is applied twice — here on the baked cards, and again in
  // js/testimonials.js — so it is published on the container rather than retyped there.
  testimonialsHtml = setStaggerAttrs(testimonialsHtml, testimonialsHtmlPath);
  writeGenerated(testimonialsHtmlPath, testimonialsHtml);
  console.log(`Wrote explore/testimonials.html — ${testimonials.length} cards, stagger ${STAGGER_STEP}s/card capped at ${STAGGER_CAP}s`);

  // --- blogs ----------------------------------------------------------
  const blogsJsonPath = path.join(ROOT, "blogs/blogs.json");
  const blogs = JSON.parse(fs.readFileSync(blogsJsonPath, "utf8"))
    .sort((a, b) => parseBlogDate(b.date) - parseBlogDate(a.date));
  checkBlogsData(blogs);

  // --- explore.html ---------------------------------------------------
  const exploreHtmlPath = path.join(ROOT, "explore.html");
  let exploreHtml = fs.readFileSync(exploreHtmlPath, "utf8");
  const slides = sortTestimonialsForCarousel(testimonials).map(renderTestimonialSlide).join("\n");
  exploreHtml = injectBetweenMarkers(exploreHtml, "testimonials-carousel", slides);
  const recentBlogs = blogs.slice(0, 3).map(b => renderBlogCard(b)).join("\n");
  exploreHtml = injectBetweenMarkers(exploreHtml, "recent-blogs", recentBlogs);
  writeGenerated(exploreHtmlPath, exploreHtml);
  console.log(`Wrote explore.html — ${sortTestimonialsForCarousel(testimonials).length} carousel slides + 3 recent blogs`);

  // --- blog-main.html -------------------------------------------------
  const blogMainPath = path.join(ROOT, "blog-main.html");
  let blogMainHtml = fs.readFileSync(blogMainPath, "utf8");
  const blogCards = blogs.map((b, i) => renderBlogCard(b, { pageNum: blogPage(i) })).join("\n");
  blogMainHtml = injectBetweenMarkers(blogMainHtml, "blog-cards", blogCards);
  // The same split happens twice — here, and again in js/search.js when a search re-pages
  // the cards — so the build states it in the markup and the JS reads it off the container
  // instead of a second typed copy of the 6.
  blogMainHtml = setPageSizeAttr(blogMainHtml, blogMainPath);
  writeGenerated(blogMainPath, blogMainHtml);
  console.log(`Wrote blog-main.html — ${blogs.length} blog cards, ${BLOG_PAGE_SIZE} per page`);

  // --- about/syllabus.html --------------------------------------------
  const syllabusPath = path.join(ROOT, "about/syllabus.html");
  let syllabusHtml = fs.readFileSync(syllabusPath, "utf8");
  const semesters = syllabusSources();
  if (!semesters.length) throw new Error("No about/syllabus-sNsM.csv files found");

  let syllabusRowCount = 0;
  const semesterData = [];
  for (const sem of semesters) {
    const marker = `syllabus-${sem.id}`;
    const grid = parseCSVGrid(fs.readFileSync(path.join(ROOT, "about", sem.file), "utf8"));
    const header = grid.shift() || [];
    const colCount = syllabusHeadCols(syllabusHtml, marker);
    if (header.length !== colCount) {
      throw new Error(
        `about/${sem.file} has ${header.length} columns but <table id="${marker}"> ` +
        `declares ${colCount} <th>. Update the <thead> and the CSV together.`
      );
    }
    // Which column holds the date; its ISO form feeds the JSON-LD schedule below.
    const dateIdx = header.findIndex(h => /date/i.test(h));
    const rows = grid.map(r => renderSyllabusRow(r, colCount)).join("\n");
    syllabusHtml = injectBetweenMarkers(syllabusHtml, marker, rows);
    syllabusRowCount += grid.length;

    const dates = grid.map(r => syllabusIsoDate(r[dateIdx])).filter(Boolean).sort();
    if (dates.length !== grid.length) {
      throw new Error(`about/${sem.file} has ${grid.length - dates.length} row(s) whose Date is not M/D/YY`);
    }
    semesterData.push({
      id: sem.id, header, rows: grid, dates, dateIdx,
      topicIdx: header.findIndex(h => /lecture topic/i.test(h)),
    });
  }

  syllabusHtml = injectBetweenMarkers(syllabusHtml, "syllabus-jsonld", buildSyllabusJsonLd(semesterData));

  // A table with no marker pair would silently ship an empty <tbody> — exactly the
  // bug this whole section exists to fix, and check:generated would not catch it
  // because the output would still be deterministic. Fail loudly instead.
  const declaredTables = [...syllabusHtml.matchAll(/<table[^>]*id="(syllabus-[a-z0-9]+)"/gi)].map(m => m[1]);
  const bakedTables = new Set(semesters.map(sem => `syllabus-${sem.id}`));
  const unbaked = declaredTables.filter(id => !bakedTables.has(id));
  if (unbaked.length) {
    throw new Error(
      `about/syllabus.html declares table(s) with no baked rows: ${unbaked.join(", ")}. ` +
      `Each needs a matching about/syllabus-<id>.csv and a <!-- BUILD:<id> --> marker pair.`
    );
  }

  writeGenerated(syllabusPath, syllabusHtml);
  console.log(`Wrote about/syllabus.html — ${semesters.length} syllabus table(s), ${syllabusRowCount} rows, JSON-LD for ${semesterData[0].rows.length} current-semester sections`);

  // --- signup.html tier class lists ------------------------------------
  const classes = yaml.load(fs.readFileSync(path.join(ROOT, "data/classes.yaml"), "utf8"), { schema: yaml.CORE_SCHEMA });
  if (!Array.isArray(classes) || !classes.length) throw new Error("data/classes.yaml has no entries");
  const signupPath = path.join(ROOT, "signup.html");
  let signupHtml = fs.readFileSync(signupPath, "utf8");
  for (const tier of [1, 2, "full"]) {
    signupHtml = injectBetweenMarkers(signupHtml, `tier-${tier}`, renderTier(classes, tier));
  }
  writeGenerated(signupPath, signupHtml);

  // about.html: the class each instructor teaches, with when it meets.
  const aboutPath = path.join(ROOT, "about.html");
  let aboutHtml = fs.readFileSync(aboutPath, "utf8");
  const anchors = [...aboutHtml.matchAll(/<!--\s*BUILD:teaches-([a-z]+)\s*-->/g)].map(m => m[1]);
  for (const a of anchors) {
    aboutHtml = injectBetweenMarkers(aboutHtml, `teaches-${a}`, renderTeaches(classes, a));
  }
  writeGenerated(aboutPath, aboutHtml);

  // index.html staff cards: the class each instructor teaches, under their name.
  const idxPath = path.join(ROOT, "index.html");
  let idxHtml = fs.readFileSync(idxPath, "utf8");
  for (const a of [...idxHtml.matchAll(/<!--\s*BUILD:teaches-index-([a-z]+)\s*-->/g)].map(m => m[1])) {
    idxHtml = injectBetweenMarkers(idxHtml, `teaches-index-${a}`, renderTeachesShort(classes, a));
  }
  writeGenerated(idxPath, idxHtml);
  console.log(`Wrote signup.html + about.html — ${classes.length} class types across 3 tiers, ${anchors.length} instructor cards`);

  // --- index.html results chart ---------------------------------------
  const resultsCsv = path.join(ROOT, "data/results.csv");
  if (!fs.existsSync(resultsCsv)) {
    throw new Error("data/results.csv is missing — it is the source of truth for every " +
      "finalist/IBO count on the site. Restore it (it is tracked in git) and rebuild.");
  }
  const resultRows = parseCSVGrid(fs.readFileSync(resultsCsv, "utf8")).slice(1);
  if (!resultRows.length) throw new Error("data/results.csv has no data rows");
  const resultTotals = resultsTotals(resultRows);
  // Any page carrying the marker pair gets the chart: a second home is one pair of
  // comments in that page's HTML, not a change here.
  const chartHtml = renderResultsSection(resultRows);
  const chartPages = ["index.html", "signup.html"].filter(
    (rel) => fs.readFileSync(path.join(ROOT, rel), "utf8").includes("<!-- BUILD:results-chart -->")
  );
  for (const rel of chartPages) {
    const full = path.join(ROOT, rel);
    writeGenerated(full, injectBetweenMarkers(fs.readFileSync(full, "utf8"), "results-chart", chartHtml));
  }
  {
    const rel = "signup.html", full = path.join(ROOT, rel);
    writeGenerated(full, injectBetweenMarkers(
      fs.readFileSync(full, "utf8"), "signup-disclaimer", renderSignupDisclaimer()));
    console.log(`Wrote signup disclaimer — refunds close the day before courseStartIso`);
  }

  console.log(`Wrote results chart — ${resultRows.length} seasons (${resultTotals.finalists} finalists, ${resultTotals.ibo} IBO) into ${chartPages.join(", ")}`);
  checkResultClaims(resultTotals);

  // --- sitemap.xml ----------------------------------------------------
  const sitemapPath = path.join(ROOT, "sitemap.xml");
  const { xml: sitemap, skipped: noindexed } = buildSitemap(photos, blogs);
  writeGenerated(sitemapPath, sitemap);
  const urlCount = (sitemap.match(/<loc>/g) || []).length;
  console.log(`Wrote sitemap.xml — ${urlCount} URLs, ${photos.length} gallery images indexed`);
  if (noindexed.length) {
    console.log(`  skipped ${noindexed.length} noindexed page(s) — their own ` +
      `<meta name="robots"> says so: ${noindexed.join(", ")}`);
  }

  // `npm run -s list:generated`, not `npm run list:generated`: npm prints its own banner
  // on STDOUT ahead of the payload, so the unsilenced form feeds banner lines to `git add`
  // as filenames. -s suppresses it, leaving exactly the ledger, one path per line.
  console.log(`Build owns ${GENERATED.size} file(s) — \`npm run -s list:generated\` prints them for staging (-s: npm's banner is on stdout)`);
  if (LIST_MODE) process.stdout.write([...GENERATED].sort().join("\n") + "\n");
  warnUntrackedBuildDeps();
  if (missingGuards.length) {
    console.warn(`\n!!  ${missingGuards.length} GUARD(S) DID NOT RUN: ${missingGuards.join(", ")}\n` +
      `    Generated, not checked. Put the file back, or close the hole deliberately:\n` +
      `    delete its want() line here and its check: script in package.json.\n`);
  }
}

build();
